#!/usr/bin/env python3
"""Generate src/gl_thunks.inc: HLE registrations for the GL functions the game imports."""
import re, sys, os

here = os.path.dirname(os.path.abspath(__file__))
proto = re.compile(r'GL_API(?:CALL)?\s+(.+?)\s*GL_APIENTRY\s+(\w+)\s*\((.*?)\);')

def parse(path):
    out = {}
    for m in proto.finditer(open(path).read()):
        out[m.group(2)] = (m.group(1).strip(), m.group(3).strip())
    return out

gles2 = parse(os.path.join(here, 'gl2.h'))
gles1 = parse(os.path.join(here, 'gles1_gl.h'))
wanted = [l.strip() for l in open(os.path.join(here, 'gl_imports.txt')) if l.strip()]

# Implemented by hand in hle_gl.cpp.
special = {'glGetString', 'glShaderSource', 'glBindFramebuffer', 'glGetIntegerv', 'glGetBooleanv',
           'glGetFloatv', 'glDeleteFramebuffers', 'glIsFramebuffer', 'glViewport', 'glScissor',
           'glShaderBinary', 'glGetShaderSource', 'glGenFramebuffers', 'glGenRenderbuffers',
           'glBindRenderbuffer', 'glDeleteRenderbuffers', 'glIsRenderbuffer', 'glFramebufferRenderbuffer',
           'glGetFramebufferAttachmentParameteriv', 'glCompressedTexImage2D', 'glCompileShader', 'glLinkProgram',
           'glUniform1f', 'glUniform2f', 'glUniform3f', 'glUniform4f', 'glUniform1fv', 'glUniform2fv', 'glUniform3fv',
           'glUniform4fv', 'glUniform1i', 'glUniform1iv', 'glUniform2iv', 'glUniform3iv', 'glUniform4iv',
           'glBindBuffer', 'glVertexAttribPointer', 'glEnableVertexAttribArray', 'glDisableVertexAttribArray',
           'glDrawElements', 'glDrawArrays'}

lines = ['// Generated by tools/gen_gl_thunks.py - do not edit.', '']
direct, manual, missing = [], [], []
for name in wanted:
    if name in special:
        manual.append(name)
    elif name in gles2:
        direct.append(name)
    else:
        missing.append(name)

for name in missing:
    ret, params = gles1.get(name, ('void', ''))
    lines.append('static void gles1_%s(Cpu &cpu) { gles1_unsupported(cpu, "%s"); }' % (name, name))
lines.append('')
lines.append('static void register_gl_thunks() {')
for name in direct:
    lines.append('    hle::reg("%s", HLE_WRAP(::%s));' % (name, name))
for name in missing:
    lines.append('    hle::reg("%s", gles1_%s);' % (name, name))
lines.append('}')
open(os.path.join(here, '..', 'src', 'gl_thunks.inc'), 'w').write('\n'.join(lines) + '\n')
print('direct', len(direct), 'manual', len(manual), 'gles1-only', len(missing))
print('manual:', ' '.join(manual))
print('gles1-only:', ' '.join(missing))
